name: word_search
version: 0.1.2
description: A word search puzzle generator built with dart.This library allows you to create a puzzle from a list of input words that can be arranged in many orientations.

repository: https://github.com/nisheed2440/word_search.dart
homepage: https://github.com/nisheed2440/word_search.dart
issue_tracker: https://github.com/nisheed2440/word_search.dart/issues

environment:
    sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
    test: ^1.14.5
    test_coverage: ^0.4.1